#if canImport(LocalDictationSpeech)
import LocalDictationSpeech

typealias OwnedModelManifest = LocalDictationSpeech.OwnedModelManifest
typealias OwnedModelInstallation = LocalDictationSpeech.OwnedModelInstallation
typealias ModelInstallation = LocalDictationSpeech.ModelInstallation
typealias OwnedModelStoreError = LocalDictationSpeech.OwnedModelStoreError
typealias OwnedModelStore = LocalDictationSpeech.OwnedModelStore
#endif
